feat: Реализация диалогового окна сброса пароля
val-hero/AtYourService pull request #20
Opened 2023-07-20 09:45 UTC by manualcheg

Добавлена разметка и класс фрагмента диалога, вспомогательные файлы фигур с различными закруглениями.
Используется кастомная разметка для DialogFragment.
Цвета, при реализации поддержки тем, нужно будет подставить подходящие.
Также в приложение добавлена поддержка binding.

2023-07-21 19:19 UTC, val-hero commented
В dev добавлен экран авторизации, можешь подтянуть изменения и доработать (навесить onClick и показ фрагмента). Там нужно будет решить конфликты с merge, напиши если будут сложности

2023-07-22 11:49 UTC, manualcheg commented
Подключил обработку к надписи "forgot password".
Прошу повторного ревью.

2023-07-22 16:28 UTC, val-hero requested changes

2023-07-22 16:28 UTC, val-hero commented on app/src/main/java/com/atyourservice/auth/resetpass/ui/ResetpassDialogFragment.kt
> +        }
Давай обернём в dialog?.window?.let { }, чтобы избавиться от if и non-null (!!) операторов, красивее будет

2023-07-22 16:28 UTC, val-hero commented on app/src/main/java/com/atyourservice/auth/ui/AuthorizationFragment.kt
> +            myResetpassDialogFragment.show(manager, TAG_RESETPASS)
Здесь нужно использовать childFragmentManager, если верить документации. Поможет избежать проблем с изменениями конфигурации. Можно сразу передавать его в show() без дополнительной переменной

2023-07-22 16:28 UTC, val-hero commented on app/src/main/res/layout/fragment_dialog_resetpass.xml
> +    android:backgroundTint="#2B2B2C"
Тут возьми цвет из ресурсов (gray)

2023-07-22 16:28 UTC, val-hero commented on app/src/main/res/values/dimens.xml
> +    <dimen name="_20sp">20sp</dimen>
16 и 20 sp уже есть в ресурсах - regular_text и main_action_text соответственно. Удали плз и замени у себя в верстке на указанные выше

2023-07-22 19:06 UTC, manualcheg commented on app/src/main/java/com/atyourservice/auth/resetpass/ui/ResetpassDialogFragment.kt
> +        }
ок

2023-07-22 19:18 UTC, manualcheg commented on app/src/main/java/com/atyourservice/auth/ui/AuthorizationFragment.kt
> +            myResetpassDialogFragment.show(manager, TAG_RESETPASS)
Сделал согласно документации

2023-07-22 19:20 UTC, manualcheg commented on app/src/main/res/layout/fragment_dialog_resetpass.xml
> +    android:backgroundTint="#2B2B2C"
Заменил

2023-07-22 19:26 UTC, manualcheg commented on app/src/main/res/values/dimens.xml
> +    <dimen name="_20sp">20sp</dimen>
Хорошо

2023-07-22 19:33 UTC, val-hero commented
Супер, можно мерджить

2023-07-22 19:33 UTC, val-hero approved these changes

2023-07-22 19:34 UTC, merged